# Generated by Django 6.0.4 on 2026-04-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
