# Generated by Django 6.0.3 on 2026-04-21 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0002_alter_customerinfo_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='zip_code',
        ),
    ]
