# Generated by Django 6.0.3 on 2026-04-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0003_remove_customerinfo_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_trending',
            new_name='is_hot_sale',
        ),
        migrations.AddField(
            model_name='product',
            name='has_gift_wrap',
            field=models.BooleanField(default=False, help_text="إضافة زخرفة 'هدية' للمنتج"),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_end_time',
            field=models.DateTimeField(blank=True, help_text='تاريخ انتهاء عرض الـ Hot Sale', null=True),
        ),
    ]
