# Generated by Django 6.0.3 on 2026-04-22 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0004_rename_is_trending_product_is_hot_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty',
        ),
        migrations.DeleteModel(
            name='AdditionalInformation',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
